apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api-cep.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api-cep.desafio.com  # Adicione o seu domínio aqui
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "api-cep.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
